extends Node

var game_lunched = false
var game_time := 0.0
var update_timer := 0.0
func _ready():
	TranslationServer.set_locale(Settings.LANGUAGE)
	
func _process(delta):
	
	game_time += delta #* Settings.TIME_SCALE
	#print(game_time)
	update_timer += delta #* Settings.TIME_SCALE
	if update_timer >= Settings.UPDATE_INTERVAL:
		update_timer = 0.0

func format_number(num: int) -> String:
	var s = str(int(num))
	var result = ""
	var count = 0
	for i in range(s.length() - 1, -1, -1):
		result = s[i] + result
		count += 1
		if count % 3 == 0 and i != 0:
			result = "." + result
	return result
	
